ShopCar/Models/ErrorViewModel.cs
namespace ShopCar.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShopCar/Models/ShopCar/ShopCarCreateUpdateViewModel.cs
namespace ShopCar.Models.ShopCar
{
    public class ShopCarCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public int Price { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int ModelYear { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopCar/Models/ShopCar/ShopCarDeleteViewModel.cs
namespace ShopCar.Models.ShopCar
{
    public class ShopCarDeleteViewModel
    {
        public Guid? Id { get; set; }
        public int Price { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int ModelYear { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopCar/Models/ShopCar/ShopCarDetailsViewModel.cs
namespace ShopCar.Models.ShopCar
{
    public class ShopCarDetailsViewModel
    {
        public Guid? Id { get; set; }
        public int Price { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int ModelYear { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopCar/Models/ShopCar/ShopCarViewModel.cs
namespace ShopCar.Models.ShopCar
{
    public class ShopCarViewModel
    {
        public Guid? Id { get; set; }
        public int Price { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int ModelYear { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopCar/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ShopCar.Models;
using System.Diagnostics;

namespace ShopCar.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ShopCar/Controllers/ShopCarController.cs
using Microsoft.AspNetCore.Mvc;
using ShopCar.Core.Dto;
using ShopCar.Core.ServiceInterface;
using ShopCar.Data;
using ShopCar.Models.ShopCar;

namespace ShopCar.Controllers
{
    public class ShopCarController : Controller
    {
        private readonly CarShopContext _context;
        private readonly IShopCarServices _carServices;

        public ShopCarController(CarShopContext context, IShopCarServices shopCarServices)
        {
            _context = context;
            _carServices = shopCarServices;
        }

        public IActionResult Index()
        {
            var result = _context.Cars
                .Select(x => new ShopCarViewModel
                {
                    Id = x.Id,
                    Price = x.Price,
                    Brand = x.Brand,
                    Model = x.Model,
                    ModelYear = x.ModelYear,
                });

            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var car = await _carServices.GetAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            var vm = new ShopCarDetailsViewModel();

            vm.Id = car.Id;
            vm.Brand = car.Brand;
            vm.Model = car.Model;
            vm.ModelYear = car.ModelYear;
            vm.Price = car.Price;
            vm.CreatedAt = car.CreatedAt;
            vm.UpdatedAt = car.UpdatedAt;

            return View(vm);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ShopCarCreateUpdateViewModel car = new ShopCarCreateUpdateViewModel();

            return View("CreateUpdate", car);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ShopCarCreateUpdateViewModel vm)
        {
            var dto = new ShopCarDto()
            {
                Id = vm.Id,
                Brand = vm.Brand,
                Model = vm.Model,
                ModelYear = vm.ModelYear,
                Price = vm.Price,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
            };

            var result = await _carServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var car = await _carServices.GetAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            var vm = new ShopCarCreateUpdateViewModel();

            vm.Id = car.Id;
            vm.Brand = car.Brand;
            vm.Model = car.Model;
            vm.ModelYear = car.ModelYear;
            vm.Price = car.Price;
            vm.CreatedAt = car.CreatedAt;
            vm.UpdatedAt = car.UpdatedAt;

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(ShopCarCreateUpdateViewModel vm)
        {
            var dto = new ShopCarDto()
            {
                Id = vm.Id,
                Brand = vm.Brand,
                Model = vm.Model,
                ModelYear = vm.ModelYear,
                Price = vm.Price,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
            };

            var result = await _carServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var car = await _carServices.GetAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            var vm = new ShopCarDeleteViewModel();

            vm.Id = car.Id;
            vm.Brand = car.Brand;
            vm.Model = car.Model;
            vm.ModelYear = car.ModelYear;
            vm.Price = car.Price;
            vm.CreatedAt = car.CreatedAt;
            vm.UpdatedAt = car.UpdatedAt;

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var carId = await _carServices.Delete(id);

            if (carId == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopCar/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">Anastassia's CAR SHOP'</a>.</p>
</div>

ShopCar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopCar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarShop.styles.css" asp-append-version="true" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShopCar" asp-action="Index">Shop Car</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CarShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ShopCar/Views/ShopCar/CreateUpdate.cshtml
@model ShopCar.Models.ShopCar.ShopCarCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="UpdatedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Brand" class="col-sm-2 col-form-label">Brand</label>
            <div class="col-sm-10">
                <input asp-for="Brand" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Model" class="col-sm-2 col-form-label">Model</label>
            <div class="col-sm-10">
                <input asp-for="Model" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="ModelYear" class="col-sm-2 col-form-label">ModelYear</label>
            <div class="col-sm-10">
                <input asp-for="ModelYear" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label">Price</label>
            <div class="col-sm-10">
                <input asp-for="Price" class="form-control" />
            </div>
        </div>

        <hr />
        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="ShopCar" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="ShopCar" type="submit" class="btn btn-primary" value="Create" />
        }

        <a asp-action="index" class="btn btn-primary">Index</a>

    </form>
</div>

ShopCar/Views/ShopCar/Delete.cshtml
@model ShopCar.Models.ShopCar.ShopCarDeleteViewModel

<h1>Delete</h1>

<div>

    <h4>Kindergarten</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Brand" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Brand)
        </div>

        <div class="form-group row">
            <label asp-for="Model" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Model)
        </div>

        <div class="form-group row">
            <label asp-for="ModelYear" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModelYear)
        </div>

        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Price)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.UpdatedAt)
        </div>
    </dl>

    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" asp-controller="ShopCar" class="btn btn-success">Back</a>
    </form>
</div>

ShopCar/Views/ShopCar/Details.cshtml
@model ShopCar.Models.ShopCar.ShopCarDetailsViewModel

<h1>Delete</h1>

<div>

    <h4>Kindergarten</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Brand" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Brand)
        </div>

        <div class="form-group row">
            <label asp-for="Model" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Model)
        </div>

        <div class="form-group row">
            <label asp-for="ModelYear" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModelYear)
        </div>

        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Price)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.UpdatedAt)
        </div>
    </dl>

    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" asp-controller="ShopCar" class="btn btn-success">Back</a>
    </form>
</div>

ShopCar/Views/ShopCar/Index.cshtml
@model IEnumerable<ShopCar.Models.ShopCar.ShopCarViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="Create" asp-controller="ShopCar" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
    Shop Car
</div>
<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Price</th>
                <th scope="col">Brand</th>
                <th scope="col">Model</th>
                <th scope="col">ModelYear</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var ShopCar in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@ShopCar.Price</td>
                    <td>@ShopCar.Brand</td>
                    <td>@ShopCar.Model</td>
                    <td>@ShopCar.ModelYear</td>
                    <td>
                        <a asp-action="details" asp-controller="ShopCar" asp-route-id="@ShopCar.Id" class="btn btn-info">Details</a>
                        <a asp-action="update" asp-controller="ShopCar" asp-route-id="@ShopCar.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="ShopCar" asp-route-id="@ShopCar.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

                rowNumber += 1;
            }
        </tbody>
    </table>
</form>